# log:
#   level: DEBUG

providers:
  docker: true

entrypoints:
  web:
    address: :80

  websecure:
    address: :443

certificatesresolvers:
  myresolver:
    acme:
      httpChallenge:
        entryPoint: web
      email: ${EMAIL}
      storage: /etc/traefik/acme.json